<div>
    <form class="Form" method="post" enctype="multipart/form-data" id="form-anuncio-pro">
        <div class="Grilla">
            <div class="Grilla__xs--12 Grilla__sm--6 Grilla l-Widget">
                <header class="l-Widget__header">
                    <h3 class="l-Widget__title">Información básica del animal</h3>
                </header>
                <section class="l-Widget__body">
                    <div class="l-Widget__container">
                        <div class="__FormAnuncio">
                            <div class="Form__group">
                                <input type="text" class="Form__control" name="nombre" placeholder="Nombre">
                            </div>
                            <div class="Form__group">
                                <select class="Form__control" id="tipos" name="tipo">
                                    <option value="-1">Selecciona un tipo de animal</option>
                                    <?php foreach ($this->listadoTipo as $key => $row): ?>
                                        <option value="<?= $row->getTipo(); ?>"><?= $row->getTipo(); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="Form__group">
                                <select class="Form__control" id="razas" name="raza">
                                    <option value="-1">Selecciona una raza</option>
                                </select>
                            </div>
                            <div class="Form__group">
                                <select class="Form__control" id="estados" name="estado">
                                    <option value="-1">Selecciona un estado</option>
                                    <?php foreach ($this->listadoEstado as $key => $row): ?>
                                        <option value="<?= $row->getTipo(); ?>"><?= $row->getTipo(); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="Form__group" id="estadoAbandonado"></div>
                            <div class="Form__group">
                            <textarea name="descripcion" class="Form__control" rows="10"
                                      placeholder="Descripcion"></textarea>
                            </div>
                            <div class="Panel__footer Panel__footer--right">
                                <input type="submit" class="btn btn-info">
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="Grilla__xs--12 Grilla__sm--6 Grilla l-Widget">
                <header class="l-Widget__header">
                    <h3 class="l-Widget__title">Tarifas del animal</h3>
                </header>
                <section class="l-Widget__body">
                    <div class="l-Widget__container">
                        <ul class="L-Lista">
                            <?php
                                foreach ($this->_tarifas??array() as $key => $row):
                                    $this->renderizarInclude('includes/components/tarifas', true, array('row' => $row));
                                endforeach;
                            ?>
                        </ul>
                    </div>
                </section>
            </div>
        </div>
    </form>
</div>