<div class="container-init container">
    <div class="Alerta Alerta--informacion">
        <p>
            INFORMATICA SEGUNDA MANO : Informática de Segunda Mano - Sección de informática de ocasión. Compra venta de equipos informáticos usados. Software y hardware: Ordenadores, Portátiles, Monitores, Impresoras, PDA, Componentes,... a los mejores precios.
        </p>
    </div>
    <div class="Grilla">
        <div class="Grilla__xs--12 Grilla__sm-12 Grilla__md--5 Grilla__lg--4 Grilla__xl--3 Grilla__xxl--2">
            <div class="Panel">
                <form class="Form" method="get">
                    <div class="Form__group">
                        <select class="Form__control" name="raza" id="" tabindex="3">
                            <option value="-1">Raza de animal</option>
                            <?php foreach ($this->razaAnimales as $ky => $row): ?>
                                <option value="<?= $row->getRaza() ?>"><?= $row->getRaza() ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="Form__group">
                        <select class="Form__control" name="prov" id="provincias" tabindex="4">
                            <option value="-1">En toda España</option>
                            <?php foreach ($this->provincias as $ky => $row): ?>
                                <option value="<?= $row->getId(); ?>"><?= $row->getProvincia(); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="Form__group">
                        <select class="Form__control" name="mun" id="municipios" tabindex="4">
                            <option value="-1">Selecciona un municipio</option>
                            <?php foreach ($this->municipios as $ky => $row): ?>
                                <option value="<?= $row->getId(); ?>"><?= $row->getMunicipio(); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="Form__group">
                        <select class="Form__control" tabindex="8" name="rol">
                            <option value="-1">Particular y profesional</option>
                            <option value="part">Sólo particulares</option>
                            <option value="prof">Sólo profesionales</option>
                        </select>
                    </div>
                    <div class="Panel__footer--right">
                        <button class="Button Button--neutral">Buscar</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="listado-anuncios Grilla__xs--12 Grilla__sm--12 Grilla__md--7 Grilla__lg--8 Grilla__xl--9 Grilla__xxl--10">
            <div class="anuncios Grilla">
                <?php foreach ($this->_listadoAnuncios as $key => $row): ?>
                    <div class="Grilla__md--12 Grilla__xs--12 Grilla__sm--6 Grilla__lg--6 Grilla__xl--4 Grilla__xxl--3">
                        <?php $this->renderizarInclude('includes/components/anuncio', true, array('row' => $row)); ?>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php
            if (isset($this->_paginator)) {
                echo $this->_paginator;
            }
            ?>
        </div>
    </div>
</div>